seed: seeds.txt
r: 0.5
# self_loops: Are self-loops allowed? 1 yes, 0 not
self_loops: 0
# eta: Restart probability for each multiplex. Must sum up to one.
eta: [1]
#4. Inter multiplex Networks Jump Probability (lambda)
lamb:
    - [1]
multiplex:
    1:
        layers:
            - multiplex/1/interactome_human.tsv
        delta: 0.5
        # Graph type: unweighted/weighted, undirected/directed
        graph_type: [10]
        # Restart probabily 3. Layers Restart Probability (tau)
        tau: [1]
